sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - CS_CHECK=true
    - php: 7
    - php: 7.1
    - php: hhvm 
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source
  - composer info -i

script:
  - composer test
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer license-check ; fi

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false
